IaC - RDS Aurora
devopsacademyau/2020-feb-project1-group2 pull request #15
Opened 2020-04-14 13:01 UTC by starkmatt

2020-04-14 13:06 UTC, starkmatt commented
Next step is seeing if we can connect our WP-Instance to this DB>

2020-04-17 10:04 UTC, kikobr82 requested changes

2020-04-17 10:04 UTC, kikobr82 commented on terraform-rds/provider.tf
> +}
not required. there should be a single provider for all resources

2020-04-17 10:04 UTC, kikobr82 commented on terraform-rds/rds.tf
> +}
File is not in the right folder.
Missing several things related to the requirements.

2020-04-18 07:41 UTC, closed without merging