Added random password creation
devopsacademyau/2020-feb-project1-group2 pull request #71
Opened 2020-04-30 10:35 UTC by deniseddi

Used `random_password` for our values instead of a string that would later have to be modified manually via aws console. It creates a random password, not displayed in console output that is saved in the parameter store.

2020-04-30 11:16 UTC, kikobr82 requested changes

2020-04-30 11:16 UTC, kikobr82 commented on terraform/parameter_store.tf
>    name        = "/wordpress/WORDPRESS_DB_USER"
you should use the value that coorespond to the secret.. in that case the db-username

2020-04-30 11:16 UTC, kikobr82 commented on terraform/parameter_store.tf
> +  value       = random_password.value.result
you should use the value that coorespond to the secret.. in that case the db-name

2020-04-30 11:16 UTC, kikobr82 commented on terraform/parameter_store.tf
>    name        = "/wordpress/WORDPRESS_DB_HOST"
you should use the value that correspond to the secret.. in that case the db-host

2020-05-08 11:11 UTC, starkmatt approved these changes
Good Stuff :-)

2020-05-10 05:33 UTC, closed without merging